# Generated by Django 4.2.2 on 2023-06-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(max_length=32)),
                ('razza', models.CharField(max_length=32)),
                ('eta', models.IntegerField(default=0)),
                ('descrizione', models.CharField(max_length=128)),
                ('stato', models.CharField(choices=[('ADOTTATO', 'adottato'), ('NON_ADOTTATO', 'non adottato'), ('IN_ATTESA', 'in attesa di conferma')], default='non adottato', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloAdozione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCognome', models.CharField(max_length=64)),
                ('indirizzo', models.CharField(max_length=128)),
                ('recapito', models.CharField(max_length=128)),
                ('animale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifugioAnimali.animale')),
            ],
        ),
    ]
