# Generated by Django 4.2.2 on 2023-06-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(max_length=32)),
                ('razza', models.CharField(max_length=32)),
                ('eta', models.IntegerField(default=0)),
                ('descrizione', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('cognome', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128)),
                ('lavoro', models.CharField(max_length=64)),
                ('codiceImpiegato', models.IntegerField(default=0)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ModuloAdozione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCognome', models.CharField(max_length=64)),
                ('indirizzo', models.CharField(max_length=128)),
                ('recapito', models.CharField(max_length=128)),
                ('animale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifugioAnimali.animale')),
                ('richiedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifugioAnimali.utente')),
            ],
        ),
    ]
