# Generated by Django 4.2.1 on 2023-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugioAnimali', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animale',
            name='descrizione',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
