# Generated by Django 4.2.2 on 2023-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugioAnimali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animale',
            name='stato',
            field=models.CharField(choices=[('ADOTTATO', 'adottato'), ('NON_ADOTTATO', 'non adottato'), ('IN_ATTESA', 'in attesa di conferma')], default='non adottato', max_length=32),
        ),
    ]
