# Generated by Django 4.2.1 on 2023-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugioAnimali', '0002_alter_animale_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloadozione',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='moduloadozione',
            name='nomeCognome',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='moduloadozione',
            name='recapito',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
