# Generated by Django 4.2.1 on 2023-06-26 15:30

from django.db import migrations, models
import rifugioAnimali.models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugioAnimali', '0004_alter_moduloadozione_indirizzo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animale',
            name='razza',
            field=models.CharField(max_length=32, validators=[rifugioAnimali.models.validate_nonempty_string]),
        ),
        migrations.AlterField(
            model_name='animale',
            name='specie',
            field=models.CharField(max_length=32, validators=[rifugioAnimali.models.validate_nonempty_string]),
        ),
        migrations.AlterField(
            model_name='animale',
            name='stato',
            field=models.CharField(choices=[('ADOTTATO', 'adottato'), ('NON_ADOTTATO', 'non adottato'), ('IN_ATTESA', 'in attesa di conferma')], default='non adottato', max_length=32, validators=[rifugioAnimali.models.validate_nonempty_string]),
        ),
        migrations.AlterField(
            model_name='moduloadozione',
            name='indirizzo',
            field=models.CharField(max_length=128, validators=[rifugioAnimali.models.validate_nonempty_string]),
        ),
        migrations.AlterField(
            model_name='moduloadozione',
            name='nomeCognome',
            field=models.CharField(max_length=64, validators=[rifugioAnimali.models.validate_nonempty_string]),
        ),
        migrations.AlterField(
            model_name='moduloadozione',
            name='recapito',
            field=models.CharField(max_length=128, validators=[rifugioAnimali.models.validate_nonempty_string]),
        ),
    ]
