# Generated by Django 4.2.1 on 2023-06-26 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifugioAnimali', '0005_alter_animale_razza_alter_animale_specie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animale',
            name='eta',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
